group:
  - climabench
dataset_path: ClimatePolicyRadar/national-climate-targets
dataset_name: null
dataset_kwargs: null
training_split: train
validation_split: train

description: "{{description}}"

doc_to_target: label
doc_to_choice: ["A", "B"]
output_type: multiple_choice

process_results: !function utils.process_results_mcq
metric_list:
  - metric: acc
  - metric: precision
    aggregation: !function utils.precision_aggr
    higher_is_better: true
  - metric: recall
    aggregation: !function utils.recall_aggr
    higher_is_better: true
  - metric: f1
    aggregation: !function utils.f1_aggr
    higher_is_better: true